### ISSUE TITLE
Geo location from message

### ISSUE THREAD

**Issue by bad-louis** [huzergackl/node-red-contrib-time-switch#12]
**Is your feature request related to a problem? Please describe.**
I have the geo coordinates in two fields in my message (lat and lon) and would like to use these instead of the configurable ones.

**Describe the solution you'd like**
Use the configured coordinates only if certain fields in the message are not filled.

**Describe alternatives you've considered**
Currently none possible.

**Comment by devRoemer** [comment]
I'll have a look at this. Should not be too complicated to implement.

**Comment by devRoemer** [comment]
Implemented in 1.1.0. Furthermore this version has improved error messages for invalid geo locations.

Have a look at the documentation to find out how to use it. You can now use placeholders in the geo loaction to use any global, flow or message value.
