### ISSUE TITLE
Please consider node-red-contrib- naming guidelines

### ISSUE THREAD

**Issue by knolleary** [huzergackl/node-red-contrib-time-switch#2]
Hi there - thanks for creating a node and sharing it with the community.

One request - as per our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging), we ask that 3rd party nodes use the `node-red-contrib-` prefix to their name. This ensures they don't get mistaken for nodes maintained by the project itself.

You're under no obligation to change the name, but I hope you'll consider it.

Many thanks, Nick

**Comment by ghost** [comment]
Hi Nick,

thats my bad. I completely overlooked that in your packaging guidlines.
I already made an unpublish request to npmjs (thats possible within 72 hours after publishing).
Furthermore i will rename the project to node-red-contrib-time-switch.

Thanks for the note.
Stefan

**Comment by ghost** [comment]
project has been renamed. new nuget package released. the old one got removed from npmjs.
