### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by AndKe** [huzergackl/node-red-contrib-time-switch#24]
please add a similar item that would have an input - being able to block/pass thru an incoming msg. based on time.

**Comment by devRoemer** [comment]
Can you give me an example on your use case. I am not sure, if i got right what you want to accomplish.

**Comment by AndKe** [comment]
Being new to nodered - I thought it would be nice to have a connection on the left side, and one(as is) on the right

![image](https://user-images.githubusercontent.com/1468842/229272340-d8b57fe4-8185-49fd-8609-ac89a138b7d1.png)

- then be able to put it in "series" of a flow, simply blocking further execution depending on time.  :)

**Comment by devRoemer** [comment]
Seems to be an invalid issue. The screenshot shows another node (other library - not mine).
Mine has two outputs. If one of these is not connected, the desired behavior to "block" an incoming message can be accomplished.
